name: Cppcheck 
run-name: Cppcheck is testing your code for static failures
on: [push]

jobs:
  Cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install cppcheck 
        run: |
          sudo apt install cppcheck
      - name: Check
        run: |
          cppcheck --suppress=missingIncludeSystem --suppress=integerOverflow --error-exitcode=2 -iASF -ioled -itouch -iconfig .
